os: Windows Server 2012 R2
platform:
  - x64
install:
#  - git submodule update --init --recursive
  - ps: Enable-PSRemoting -Force
  - winrm quickconfig -q
  - winrm set winrm/config/client @{TrustedHosts="*"}
  - winrm set winrm/config/client/auth @{Basic="true"}
  - winrm set winrm/config/service/auth @{Basic="true"}
  - winrm set winrm/config/service @{AllowUnencrypted="true"}
  - echo %PATH%
  - ruby --version
  - gem list
  - python -V
  - pip list
