os: Windows Server 2012 R2
platform:
  - x64
matrix:
# first group
  - ruby_version: "22-x64"
    python_version: "27-x64"

install:
#  - git submodule update --init --recursive
  - ps: Enable-PSRemoting -Force
  - winrm quickconfig -q
  - winrm set winrm/config/client @{TrustedHosts="*"}
  - winrm set winrm/config/client/auth @{Basic="true"}
  - winrm set winrm/config/service/auth @{Basic="true"}
  - winrm set winrm/config/service @{AllowUnencrypted="true"}
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\Python%python_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem list
  - python -V
  - cinst pip
  - pip list
