os: Windows Server 2012 R2
platform:
  - x64
environment:
  TIMEOUT: "60m"
  matrix:
  # first group
    - ruby_version: "22-x64"
      python_version: "27-x64"

install:
#  - git submodule update --init --recursive
  - ps: Enable-PSRemoting -Force
  - winrm quickconfig -q
  - winrm set winrm/config/client @{TrustedHosts="*"}
  - winrm set winrm/config/client/auth @{Basic="true"}
  - winrm set winrm/config/service/auth @{Basic="true"}
  - winrm set winrm/config/service @{AllowUnencrypted="true"}
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\Python%python_version%\;%PATH%
  - SET PATH=C:\Python%python_version%\Scripts;%PATH%
  - echo %PATH%
  - ruby --version
  - gem install highline --no-ri --no-rdoc
  - gem install ansible_spec --no-ri --no-rdoc
  - net user appveyor %TARGET_PASSWORD% # set webui
#  - python -V
#  - choco list
#  - cinst -y virtualbox docker docker-machine
#  - cinst -y pip
#  - pip list

build_script:
  - "rake serverspec:check_serverspec"
#  - docker-machine.exe -v
#  - docker-machine.exe ls
  #- docker-machine.exe create --driver virtualbox dev
  # "Hyper-V is installed. VirtualBox won't boot a 64bits VM when Hyper-V is activated. If it's installed but deactivated, you can use --virtualbox-no-vtx-check to try anyways"
#  - SET VIRTUALBOX_NO_VTX_CHECK=True
#  - docker-machine.exe create --driver virtualbox dev
#  - docker-machine.exe ls
